### ISSUE TITLE
Error when trying to update node.

### ISSUE THREAD

**Issue by FlorianWendelborn** [perfusorius/nuw#1]
```
>nuw update

>"nuw\bin\nuw.cmd"   update
Updating ...

nuw\lib\index.js:87
    return (ver.split('.')[1] % 2 == 0);
                ^
TypeError: Cannot call method 'split' of null
    at isStableVersion (nuw\lib\index.js:87:17)
    at Socket.<anonymous> (nuw\lib\index.js:161:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:528:21)
```

**Comment by perfusorius** [comment]
@FlorianWendelborn Could you please submit the version numbers of your windows, node and npm? Thank you

**Comment by FlorianWendelborn** [comment]
```
>npm --version
1.4.3
```

```
>ver
Microsoft Windows [Version 6.1.7601]
```

(Windows 7 Ultimate 64-bits)

```
>node --version
v0.10.26
```

**Comment by perfusorius** [comment]
@FlorianWendelborn Is fixed now, will publish update to npm later today.
